
### Refresh token of the user logged in
POST http://localhost:3000/api/auth/refresh HTTP/1.1
x-auth-token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZWI2NjQzMjBjYTU1YTAwYmU5NDEzNyIsInVzZXJuYW1lIjoiTGF1cmVuY2UzMyIsImlhdCI6MTY1OTU5NDMzOSwiZXhwIjoxNjU5NTk1MjM5fQ.PUKZRIl_4xnxTZuwMGTNWZH60JGryIP4kcOnrLlaurbD6-THtTN9nRBWnUtudDeaLXyjQTmgKRzneOYIM3JQ4o1KOKXJ_Lp_7YPWynlf9W0_2LGEZ9arYlR7B2JZMtNHHyaqBRoNKRm_VNJ70PvUou454gQBtks3deOOcQ2ij1wVtihlRdjW_USUzta_DbMreXH5_rKxjQCnHabvSF7fXlhmcHfLidopG5no3tB3x3wdIIa-03maZTfXGwotYB_T_lu1nx5CQX5u5-8_KG1SYr3bk5FIj_U_i3iLdmg2uxAU3gTALYFc3fGb7FVokksuabmBYx6fC0XHUVzxAe-B1HxGbgdGYzlOSp7y1NyWvMQEZDSnTToPVyqEukFozaNaxstBjYZpPDAcdHmYcTNhISXJdysdCmPVy7VRq-sy89XP1_2CwvkQVrsVJXKuOV9kfwx35vftHjSATR6KahTpz5qR2N2_d-hF39uoHya76zaFzR_IqrYJX0Cy22KE3Ci0J112bwPIY2O77qOhO_dx_HepWN448BSSjkBQ1T-sRQlaxlz4zEfTxVwL7HizARuqNg5NvpH4hxKRHS9gUvHRm9TL3j9e1DyMTc9dmmWRfFKRdlH9BAI8FqQIiEYvu7zMUd8W1U8AD2N7PJuvHHu9CL8fRO6NBWMuuN7hujNS5dM
Cookie: refresh-token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZWI2NjQzMjBjYTU1YTAwYmU5NDEzNyIsInVzZXJuYW1lIjoiTGF1cmVuY2UzMyIsImlhdCI6MTY1OTU5NDMzOSwiZXhwIjoxNjYyMTg2MzM5fQ.PuYxbrW0tbAJhgdZXtiqkJKL-ZKWhGNaizG_fJGUjCWVb2uoFs9ZqfWYG28A7ixlwhodNssCYlVUWnG3L448wJUZ3_z_7YbA_y643jQW4LSdVjWO6nu3brirRI3yXZPBGZbgXvqQgXpHWJwMftC5gf9UjAvho5hO00H0vIsoJVxWXjy1KAnh3JqZ6DNkHjvoYD6rDqlOi0_2QfjPvtk1EDBDhnVyEdJnzCJc4-72zl5aekvzYPU99num3hteZo-3efRwVK11yt_iGGOYcxSKn1nQUxOJS4nljoLheg8ca7Z-2X-K8tzuwxDbnKqJIyMFRzMKshKhci0z6nHtnRe_xvFpdXem-F3Oa4ZWztv8O8evBro6bpO4cDqe4O5B5QO2jzn8Hlez1_5wVOD4WkeNLZFftkJHM2d6IFyuw61punWzjHK1-8C3xSBiR2-D2HHj66ORj3jWcFJLUEg5bV3SbhJxJurnPLKjMOxH0L3dLAFC0U8mCxedVm09lCzzvCwn6q2mkoz6zOO1v9iSPzoLJeU5QGd2Y7ytnJUeJ1yFuaaeKWFkXJRh-gSUxmlm1EkGdGDtiEaeknLmOP5jgGFVSUn_18qMJVNqdY2Z1KpWxS7z0EZziNiTPG8vqlJTueRYvsYtauk3AOOIIj8ZjidIlVH5Rk9IrwU83uFqJfsVb-8


### Get all post by the user logged in
GET http://localhost:3000/api/posts HTTP/1.1
x-auth-token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZWI2NjQzMjBjYTU1YTAwYmU5NDEzNyIsInVzZXJuYW1lIjoiTGF1cmVuY2UzMyIsImlhdCI6MTY1OTU5NDYwNCwiZXhwIjoxNjU5NTk1NTA0fQ.LecRoOh-ynIbMN_xrUL0kbAMnu8G-3BPgg75xBES3avQyd-Xw3YU8Au9TY_xKrDJuvoNN-hjadxc1PIgy5GdN1oUERWmAWluerqygc2qS690WvGPDVv5o-Dw19kg5wzagUSYWRmwuL_AVzn7R_qlXugMeSFBsuKEFa40JfuVPxdj2tnh_PtSaNp8zx50zd-7KgoUxbwBYSrvAZBxrZwPPd7e_naEEswMnLK4HrzEpYQdbpnRcbV4Wtp_lwYaJC2SZ1kbFfOmD3st-VcT5hWN-zcj565Tnudrj6e_k9p3w-5zLxyw590Z1dmYHmEfEVP8G8BXPtLnRz1SrHij5yJFKnk9wGkZd3BBHvzVus6greC4GGTXN5fbNeWe8NPYKmjDPULyNl4o3Kz6WsC-2hxdUawS7SjJw43n_eSPmFi9tD2Y7hxc12FbWVcKNRcqVXB29mUZEFSTRSEcUaa4MfpcrmmtqeLjU9a-V_DEOtEVycbOz56bCtvoa9YVbyDgkWJlPB5ID8PcdyRQ9mnqTm-TgXmgZRQfa0SHgJKgttRQZqbfIwGKL-xZw9vbrrzGLg780RMUWT3CHd19KD1TyDQFWLIjl8GFXHwF63XBHR33tRbAXpkmMKp9DZHPzTPXDlh6PupJ2d6ik-Rc-FwLDsSvfn6Ps6rajAaH8i6wmyfIRng
Cookie: refresh-token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZWI2NjQzMjBjYTU1YTAwYmU5NDEzNyIsInVzZXJuYW1lIjoiTGF1cmVuY2UzMyIsImlhdCI6MTY1OTU5NDYwNCwiZXhwIjoxNjYyMTg2NjA0fQ.NkGTHdEk3m7KfKofByRdeTiaf-cQbo_551YMtDC5ESy2LK2ieUzono3uQ0GfGCMo5fAOWXpwcmBCpJTy7X1p1rw3dq6K2oJiQDwt9Nrpqn6QMTU8DsaXbb2I1WjAM9wxKo1fUGmuigCW67fBvaSnzgnZNGVPMAwSfRdg3H9NDI43wCRN0Y-Wsivylb8M6RCbPyMrzDwKRkkRP4sxueok-Bt-BKFwHnxVmFMYEni3GUSjaqkHIbNl92X6fjxbWkyZjXUP1b-3zr3EA7mfUPVycuvRje5jNVYNjNAU4_Cob0OIfYOHUgFKVmz1EIzCQQpZxf84vjXPDgzx1fKooXavqS2pVwaX589H_Cd3B9dfhLN_f-q2QX-PLqObWN0bn1zOcC84urFcT3G0u454Os-RBtuOcH-cc9hs7Yy2Dr0dQcg0hhgM2l04LHci0YezVbODPH0MHvUp2ifG-w0-rp0zLNh1Yse6EvgjjRD3XUcfb2tIlxMI9HWo3xVxPBzmUUvdMujl7DzAwXqYrLPVIMzYpIsHCUd7R_jLsXg4Sb7-KaXYOEmb0T4FlOGKt-zeP11sV3P5plPLje4y6Gu-ADoA5i9k5eIClVu-XA3yDcMkgurHFUI86vc-_UvnzjPMXlypwXpKhwyzdgmTBEuIzreH0EHotlnD6_hNub7gwWaT4qk

### get a specific post
GET http://localhost:3000/api/posts/62eb671220ca55a00be94152 HTTP/1.1
x-auth-token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZWE4Nzg1ZjgyODE0MTQ4NDk5MWQzZiIsInVzZXJuYW1lIjoiTGF1cmVuY2UzMyIsImlhdCI6MTY1OTU4ODM5OCwiZXhwIjoxNjU5NTg5Mjk4fQ.mx77KQM3FBCniFm9L_Iruw5izDISIw-iAva70vTA_E-DsgOInfgGXAAxscMHEoZxNW41nqKUvFBJvlQG3UnheuUsFMELaS_x6x1j_0zf7ZlITaDWwH_hHCquHNFs1uzAXQJow2H85eyIZAZEdj5RTn7Jod95PAT3pAL4EkoBmZoSfkLkqGG54UI7sGdkOv7DaZ9RPHKt1WdPQSQ0Ck3kGTsf_i50UX0n4sfx_AfTfAUveXNWTssO3AOmTOGdD5kse1u_l_UIsHfxgKFNMZl8yi8nDGUT_lmMGazMeOEdMzxenVpfXIAgWkxDUhdfWAbA5CHAIzIk6-FoHEKPj6faKD4VoENwtGUSy1QS8VX-od8IEzmF8g0FPvLcF2hfhGzgTummzzx6yf9YLEJjeMTjWlmkU48oW4dksazH2GdkXoWlUeUFGc_vQktFdAP5vO7eVWEOMF7Vlu6N0oOBSADWn7opVRKpkjpFqg8cu1GazSN8bTUVi-sWN-DdzaekSuGe6kD_rWxgqIAZvr19kgr-sDDc8bSSdHiEWVjIQq121FdONSBIv063hJ96B1YI_xSWgmcciGcnN-xwxDnxAobr9JGhGDHOiS1ZMAmWoUBGGf1prJEGP3ORaKaLySLyKW5hfoJlywES0NF595LY_-u6dt-WCapi-ldJTLFdp87m3Rk
Cookie: refresh-token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZWE4Nzg1ZjgyODE0MTQ4NDk5MWQzZiIsInVzZXJuYW1lIjoiTGF1cmVuY2UzMyIsImlhdCI6MTY1OTU4ODM5OCwiZXhwIjoxNjYyMTgwMzk4fQ.euoHep0V7JvBVNx1gmrTi2Tsgc1CqQAIIZR1m_43i_8bSkOYUkhho2ULIEtjn7P9SdxOkU2FITzdD3ODnHlFUaveLyJh_qjt2ZQkXc1AMVf8H6SndsXVb2OIAMI-sjhQLIDqOYHqEmoEeKiOFziBZJZe6PYQOMLiA4cUbTttqqukUj4EtMtlmx0pZWdEeE48hfkjwenJ7BnvqoqchoFrf3ZvIJV9VM9nfzvgunceiGZcs-sCRJWFPwQD7mByosC3B68GR4hSdT91exQ02Nccizj-lM2oJz8J20orYvmOCFOL7UmRKJSY3R2FPctp1xy-t9mfnS0_qpZ2mQEqjkYwoN9f8P6DaBQ6CRs-WYShe8pPBKaeKXExfgmLwo0uuE7zsBUQ3oRLq8b75Z-XiPGvMHo-i0EocN2X8bxdCwNml_FPWCxmSatno1t4BI24AU2jFbXd-7W6fABLW6RE67s_xcbiMGRHgI87TRnE_adiXu8VcKhehv9gecIdbdMCgEOE527zfaZhwxI4ZR_jyL_igb_S3oECZrX6p7w2BgtIzsNj3F9DjolRdY8nnt5WD3GsVdk_QBYAYwuHi-xRGyPT6LW80o7K13GcNseamv8Cbf39wbShD-8RpJY-4F6TT8JxSVy6B8CZzw1UFfrJOu6iMrp_RXG3SsJi2rdRxf2THK8


### Get download links for images of the post
GET http://localhost:3000/api/posts/62eb671220ca55a00be94152/images HTTP/1.1
x-auth-token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZWE4Nzg1ZjgyODE0MTQ4NDk5MWQzZiIsInVzZXJuYW1lIjoiTGF1cmVuY2UzMyIsImlhdCI6MTY1OTU4ODM5OCwiZXhwIjoxNjU5NTg5Mjk4fQ.mx77KQM3FBCniFm9L_Iruw5izDISIw-iAva70vTA_E-DsgOInfgGXAAxscMHEoZxNW41nqKUvFBJvlQG3UnheuUsFMELaS_x6x1j_0zf7ZlITaDWwH_hHCquHNFs1uzAXQJow2H85eyIZAZEdj5RTn7Jod95PAT3pAL4EkoBmZoSfkLkqGG54UI7sGdkOv7DaZ9RPHKt1WdPQSQ0Ck3kGTsf_i50UX0n4sfx_AfTfAUveXNWTssO3AOmTOGdD5kse1u_l_UIsHfxgKFNMZl8yi8nDGUT_lmMGazMeOEdMzxenVpfXIAgWkxDUhdfWAbA5CHAIzIk6-FoHEKPj6faKD4VoENwtGUSy1QS8VX-od8IEzmF8g0FPvLcF2hfhGzgTummzzx6yf9YLEJjeMTjWlmkU48oW4dksazH2GdkXoWlUeUFGc_vQktFdAP5vO7eVWEOMF7Vlu6N0oOBSADWn7opVRKpkjpFqg8cu1GazSN8bTUVi-sWN-DdzaekSuGe6kD_rWxgqIAZvr19kgr-sDDc8bSSdHiEWVjIQq121FdONSBIv063hJ96B1YI_xSWgmcciGcnN-xwxDnxAobr9JGhGDHOiS1ZMAmWoUBGGf1prJEGP3ORaKaLySLyKW5hfoJlywES0NF595LY_-u6dt-WCapi-ldJTLFdp87m3Rk
Cookie: refresh-token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZWE4Nzg1ZjgyODE0MTQ4NDk5MWQzZiIsInVzZXJuYW1lIjoiTGF1cmVuY2UzMyIsImlhdCI6MTY1OTU4ODM5OCwiZXhwIjoxNjYyMTgwMzk4fQ.euoHep0V7JvBVNx1gmrTi2Tsgc1CqQAIIZR1m_43i_8bSkOYUkhho2ULIEtjn7P9SdxOkU2FITzdD3ODnHlFUaveLyJh_qjt2ZQkXc1AMVf8H6SndsXVb2OIAMI-sjhQLIDqOYHqEmoEeKiOFziBZJZe6PYQOMLiA4cUbTttqqukUj4EtMtlmx0pZWdEeE48hfkjwenJ7BnvqoqchoFrf3ZvIJV9VM9nfzvgunceiGZcs-sCRJWFPwQD7mByosC3B68GR4hSdT91exQ02Nccizj-lM2oJz8J20orYvmOCFOL7UmRKJSY3R2FPctp1xy-t9mfnS0_qpZ2mQEqjkYwoN9f8P6DaBQ6CRs-WYShe8pPBKaeKXExfgmLwo0uuE7zsBUQ3oRLq8b75Z-XiPGvMHo-i0EocN2X8bxdCwNml_FPWCxmSatno1t4BI24AU2jFbXd-7W6fABLW6RE67s_xcbiMGRHgI87TRnE_adiXu8VcKhehv9gecIdbdMCgEOE527zfaZhwxI4ZR_jyL_igb_S3oECZrX6p7w2BgtIzsNj3F9DjolRdY8nnt5WD3GsVdk_QBYAYwuHi-xRGyPT6LW80o7K13GcNseamv8Cbf39wbShD-8RpJY-4F6TT8JxSVy6B8CZzw1UFfrJOu6iMrp_RXG3SsJi2rdRxf2THK8


### Delete a post owned by the logged in user
DELETE http://localhost:3000/api/posts/62eb66e820ca55a00be94145 HTTP/1.1
x-auth-token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZWE4Nzg1ZjgyODE0MTQ4NDk5MWQzZiIsInVzZXJuYW1lIjoiTGF1cmVuY2UzMyIsImlhdCI6MTY1OTU4ODM5OCwiZXhwIjoxNjU5NTg5Mjk4fQ.mx77KQM3FBCniFm9L_Iruw5izDISIw-iAva70vTA_E-DsgOInfgGXAAxscMHEoZxNW41nqKUvFBJvlQG3UnheuUsFMELaS_x6x1j_0zf7ZlITaDWwH_hHCquHNFs1uzAXQJow2H85eyIZAZEdj5RTn7Jod95PAT3pAL4EkoBmZoSfkLkqGG54UI7sGdkOv7DaZ9RPHKt1WdPQSQ0Ck3kGTsf_i50UX0n4sfx_AfTfAUveXNWTssO3AOmTOGdD5kse1u_l_UIsHfxgKFNMZl8yi8nDGUT_lmMGazMeOEdMzxenVpfXIAgWkxDUhdfWAbA5CHAIzIk6-FoHEKPj6faKD4VoENwtGUSy1QS8VX-od8IEzmF8g0FPvLcF2hfhGzgTummzzx6yf9YLEJjeMTjWlmkU48oW4dksazH2GdkXoWlUeUFGc_vQktFdAP5vO7eVWEOMF7Vlu6N0oOBSADWn7opVRKpkjpFqg8cu1GazSN8bTUVi-sWN-DdzaekSuGe6kD_rWxgqIAZvr19kgr-sDDc8bSSdHiEWVjIQq121FdONSBIv063hJ96B1YI_xSWgmcciGcnN-xwxDnxAobr9JGhGDHOiS1ZMAmWoUBGGf1prJEGP3ORaKaLySLyKW5hfoJlywES0NF595LY_-u6dt-WCapi-ldJTLFdp87m3Rk
Cookie: refresh-token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZWE4Nzg1ZjgyODE0MTQ4NDk5MWQzZiIsInVzZXJuYW1lIjoiTGF1cmVuY2UzMyIsImlhdCI6MTY1OTU4ODM5OCwiZXhwIjoxNjYyMTgwMzk4fQ.euoHep0V7JvBVNx1gmrTi2Tsgc1CqQAIIZR1m_43i_8bSkOYUkhho2ULIEtjn7P9SdxOkU2FITzdD3ODnHlFUaveLyJh_qjt2ZQkXc1AMVf8H6SndsXVb2OIAMI-sjhQLIDqOYHqEmoEeKiOFziBZJZe6PYQOMLiA4cUbTttqqukUj4EtMtlmx0pZWdEeE48hfkjwenJ7BnvqoqchoFrf3ZvIJV9VM9nfzvgunceiGZcs-sCRJWFPwQD7mByosC3B68GR4hSdT91exQ02Nccizj-lM2oJz8J20orYvmOCFOL7UmRKJSY3R2FPctp1xy-t9mfnS0_qpZ2mQEqjkYwoN9f8P6DaBQ6CRs-WYShe8pPBKaeKXExfgmLwo0uuE7zsBUQ3oRLq8b75Z-XiPGvMHo-i0EocN2X8bxdCwNml_FPWCxmSatno1t4BI24AU2jFbXd-7W6fABLW6RE67s_xcbiMGRHgI87TRnE_adiXu8VcKhehv9gecIdbdMCgEOE527zfaZhwxI4ZR_jyL_igb_S3oECZrX6p7w2BgtIzsNj3F9DjolRdY8nnt5WD3GsVdk_QBYAYwuHi-xRGyPT6LW80o7K13GcNseamv8Cbf39wbShD-8RpJY-4F6TT8JxSVy6B8CZzw1UFfrJOu6iMrp_RXG3SsJi2rdRxf2THK8


### Search for posts by keywords, date created range, and limit the result. Default limit is 10.
GET http://localhost:3000/api/search?keyword=second HTTP/1.1


### Create post under the logged in user
POST http://localhost:3000/api/posts HTTP/1.1
Content-Type: application/json
x-auth-token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZWE4Nzg1ZjgyODE0MTQ4NDk5MWQzZiIsInVzZXJuYW1lIjoiTGF1cmVuY2UzMyIsImlhdCI6MTY1OTU4ODM5OCwiZXhwIjoxNjU5NTg5Mjk4fQ.mx77KQM3FBCniFm9L_Iruw5izDISIw-iAva70vTA_E-DsgOInfgGXAAxscMHEoZxNW41nqKUvFBJvlQG3UnheuUsFMELaS_x6x1j_0zf7ZlITaDWwH_hHCquHNFs1uzAXQJow2H85eyIZAZEdj5RTn7Jod95PAT3pAL4EkoBmZoSfkLkqGG54UI7sGdkOv7DaZ9RPHKt1WdPQSQ0Ck3kGTsf_i50UX0n4sfx_AfTfAUveXNWTssO3AOmTOGdD5kse1u_l_UIsHfxgKFNMZl8yi8nDGUT_lmMGazMeOEdMzxenVpfXIAgWkxDUhdfWAbA5CHAIzIk6-FoHEKPj6faKD4VoENwtGUSy1QS8VX-od8IEzmF8g0FPvLcF2hfhGzgTummzzx6yf9YLEJjeMTjWlmkU48oW4dksazH2GdkXoWlUeUFGc_vQktFdAP5vO7eVWEOMF7Vlu6N0oOBSADWn7opVRKpkjpFqg8cu1GazSN8bTUVi-sWN-DdzaekSuGe6kD_rWxgqIAZvr19kgr-sDDc8bSSdHiEWVjIQq121FdONSBIv063hJ96B1YI_xSWgmcciGcnN-xwxDnxAobr9JGhGDHOiS1ZMAmWoUBGGf1prJEGP3ORaKaLySLyKW5hfoJlywES0NF595LY_-u6dt-WCapi-ldJTLFdp87m3Rk
Cookie: refresh-token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZWE4Nzg1ZjgyODE0MTQ4NDk5MWQzZiIsInVzZXJuYW1lIjoiTGF1cmVuY2UzMyIsImlhdCI6MTY1OTU4ODM5OCwiZXhwIjoxNjYyMTgwMzk4fQ.euoHep0V7JvBVNx1gmrTi2Tsgc1CqQAIIZR1m_43i_8bSkOYUkhho2ULIEtjn7P9SdxOkU2FITzdD3ODnHlFUaveLyJh_qjt2ZQkXc1AMVf8H6SndsXVb2OIAMI-sjhQLIDqOYHqEmoEeKiOFziBZJZe6PYQOMLiA4cUbTttqqukUj4EtMtlmx0pZWdEeE48hfkjwenJ7BnvqoqchoFrf3ZvIJV9VM9nfzvgunceiGZcs-sCRJWFPwQD7mByosC3B68GR4hSdT91exQ02Nccizj-lM2oJz8J20orYvmOCFOL7UmRKJSY3R2FPctp1xy-t9mfnS0_qpZ2mQEqjkYwoN9f8P6DaBQ6CRs-WYShe8pPBKaeKXExfgmLwo0uuE7zsBUQ3oRLq8b75Z-XiPGvMHo-i0EocN2X8bxdCwNml_FPWCxmSatno1t4BI24AU2jFbXd-7W6fABLW6RE67s_xcbiMGRHgI87TRnE_adiXu8VcKhehv9gecIdbdMCgEOE527zfaZhwxI4ZR_jyL_igb_S3oECZrX6p7w2BgtIzsNj3F9DjolRdY8nnt5WD3GsVdk_QBYAYwuHi-xRGyPT6LW80o7K13GcNseamv8Cbf39wbShD-8RpJY-4F6TT8JxSVy6B8CZzw1UFfrJOu6iMrp_RXG3SsJi2rdRxf2THK8

{
    "title": "My first post",
    "body": "This is my third post."
}


### Register a new user
POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "username": "Laurence33",
    "password": "Pass123@"
}


### Login using username and password
POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "username": "Laurence33",
    "password": "Pass123@"
}

### Try to get all post without logging in, should return 403
POST http://localhost:3000/api/posts HTTP/1.1



### Logout the user
DELETE http://localhost:3000/api/auth/logout HTTP/1.1



