
### Refresh token of the user logged in
POST http://localhost:3000/api/auth/refresh HTTP/1.1
x-auth-token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZWI2NjQzMjBjYTU1YTAwYmU5NDEzNyIsInVzZXJuYW1lIjoiTGF1cmVuY2UzMyIsImlhdCI6MTY1OTU5NDMzOSwiZXhwIjoxNjU5NTk1MjM5fQ.PUKZRIl_4xnxTZuwMGTNWZH60JGryIP4kcOnrLlaurbD6-THtTN9nRBWnUtudDeaLXyjQTmgKRzneOYIM3JQ4o1KOKXJ_Lp_7YPWynlf9W0_2LGEZ9arYlR7B2JZMtNHHyaqBRoNKRm_VNJ70PvUou454gQBtks3deOOcQ2ij1wVtihlRdjW_USUzta_DbMreXH5_rKxjQCnHabvSF7fXlhmcHfLidopG5no3tB3x3wdIIa-03maZTfXGwotYB_T_lu1nx5CQX5u5-8_KG1SYr3bk5FIj_U_i3iLdmg2uxAU3gTALYFc3fGb7FVokksuabmBYx6fC0XHUVzxAe-B1HxGbgdGYzlOSp7y1NyWvMQEZDSnTToPVyqEukFozaNaxstBjYZpPDAcdHmYcTNhISXJdysdCmPVy7VRq-sy89XP1_2CwvkQVrsVJXKuOV9kfwx35vftHjSATR6KahTpz5qR2N2_d-hF39uoHya76zaFzR_IqrYJX0Cy22KE3Ci0J112bwPIY2O77qOhO_dx_HepWN448BSSjkBQ1T-sRQlaxlz4zEfTxVwL7HizARuqNg5NvpH4hxKRHS9gUvHRm9TL3j9e1DyMTc9dmmWRfFKRdlH9BAI8FqQIiEYvu7zMUd8W1U8AD2N7PJuvHHu9CL8fRO6NBWMuuN7hujNS5dM
Cookie: refresh-token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZWI2NjQzMjBjYTU1YTAwYmU5NDEzNyIsInVzZXJuYW1lIjoiTGF1cmVuY2UzMyIsImlhdCI6MTY1OTU5NDMzOSwiZXhwIjoxNjYyMTg2MzM5fQ.PuYxbrW0tbAJhgdZXtiqkJKL-ZKWhGNaizG_fJGUjCWVb2uoFs9ZqfWYG28A7ixlwhodNssCYlVUWnG3L448wJUZ3_z_7YbA_y643jQW4LSdVjWO6nu3brirRI3yXZPBGZbgXvqQgXpHWJwMftC5gf9UjAvho5hO00H0vIsoJVxWXjy1KAnh3JqZ6DNkHjvoYD6rDqlOi0_2QfjPvtk1EDBDhnVyEdJnzCJc4-72zl5aekvzYPU99num3hteZo-3efRwVK11yt_iGGOYcxSKn1nQUxOJS4nljoLheg8ca7Z-2X-K8tzuwxDbnKqJIyMFRzMKshKhci0z6nHtnRe_xvFpdXem-F3Oa4ZWztv8O8evBro6bpO4cDqe4O5B5QO2jzn8Hlez1_5wVOD4WkeNLZFftkJHM2d6IFyuw61punWzjHK1-8C3xSBiR2-D2HHj66ORj3jWcFJLUEg5bV3SbhJxJurnPLKjMOxH0L3dLAFC0U8mCxedVm09lCzzvCwn6q2mkoz6zOO1v9iSPzoLJeU5QGd2Y7ytnJUeJ1yFuaaeKWFkXJRh-gSUxmlm1EkGdGDtiEaeknLmOP5jgGFVSUn_18qMJVNqdY2Z1KpWxS7z0EZziNiTPG8vqlJTueRYvsYtauk3AOOIIj8ZjidIlVH5Rk9IrwU83uFqJfsVb-8


### Get all post by the user logged in
GET http://localhost:3000/api/posts HTTP/1.1
x-auth-token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZWI2NjQzMjBjYTU1YTAwYmU5NDEzNyIsInVzZXJuYW1lIjoiTGF1cmVuY2UzMyIsImlhdCI6MTY1OTU5NzM1MSwiZXhwIjoxNjU5NTk4MjUxfQ.FtQQSzMg_Kl5r1c5bJgLGynOec9PQ1D_S5eoX9HAbVR1JtpzwoO2Ni3FoRPwRKvMEyxN19rxeTV078jY8LC4t2z0v-h8riLYiiq2x9AweDdGfM0lOpaX2EBb5uXvfyf3HGI_jYmhl77cP_iIu3P3JTL3sWoJ2_z5wjQF8VqHMLWkg_mW6nyrwXj3oHe2VXg1JAeIo1jy2pOPWaEFoEUnkx_FwUGw0kw_b8I9mdALpvTJ91Y6C05LpgkqGmYKPS7pKIH4yn17_Zo0kaNSn_mkubkNdQPTnRAF3fNY2pWNiZCSoHsQB855PwSBN39wHpAQef0su5pBVL0yczA_SzOZ39-2pJ_VhMc2IFnYlxwX2lWmhpru6Lts47OLXUpSc1Cpjt1i2UYaYehqmXTnw7MBcFmwUbXnVvsszY80mtftqC56IhR_JOJ6XIdk_R3Nw96Ibj4RkSfHlOfb5aU9i55wMss5fCDV5siM_pgxun-g3_d9pYhhE8E_-6XoyJoat0Um_Cdn91OCOhj5GCKPGNr7gXJufK8U9c_KLLmj6fGIxdtXx_u3u1IdMbl5VBGlEUT8CH58qf0WVWjYjNsKrWHf1cocOpJDd3fGtlu0VVROFZCgyjpjuzLtNkjoHd1wsTsjP3yZ0eUMM5sJaHc51Q34lbLxDIB5BSwgaIctHQIccWw
Set-Cookie: refresh-token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZWI2NjQzMjBjYTU1YTAwYmU5NDEzNyIsInVzZXJuYW1lIjoiTGF1cmVuY2UzMyIsImlhdCI6MTY1OTU5NjgxMiwiZXhwIjoxNjYyMTg4ODEyfQ.f-M44Cc5b5eIYZdpQLcl4FaR7q4-ZzuWEakKiJ3HaQumnXa-Dj1WsXAsyyq0MVwPabop1iNdbREoNLMMt-Zw56J8qzB8Ya_wU2mzStStr3E24blr_hvKbLPLEm5f1uaPuaKO7Frqoguu2vMupFGyJ06Lx_5maj15d7RWL87NtDBb7i2BOIBC1WwhrS-KqK7Yw_4s5Ijyk_Sk45xFbGiGoalgnOJWj6Qyu44Vt0E7M6iMi6NlsVHexgtGpcGLkqcjR7sEXYpwNgpy48Wwcu_xHWGBWz1UX6CgSraUdS2mt_owHxOa-ArZix0oqJwZXEJR0CgIVWO0JFQQmMy40ix6gjqzgSs6ykIZ9FJzPSB9nAOZlwdmp6A4qL-1G9oOsY4mNg719kpr3LVZjUt7KXlVyTXdC3X2vSeDWyKp7el4aal9Lkt5vb0wIeqHbG8A1TM3qgDpc5V4QpXQZVL7TlWnkEcgovi4qGZaNcZKWMwaVeD6BHRl_fMYL0UGj3ci0UfOArmSJtjr5Au71IknPeoY5zWoXU8p67sDomGdVbki_f0NT3uUCwYfu_LZdlLpLoRf3bdP9_1ivs-n8sRravSKbiJ-9IZzMG3emOzXmFEEqkF-HufHLk_Z0zvmpUSp0c31vp6en7lO2a5lpOT8Sdw35aKfegyeEpsEVStFBCpQey0



### get a specific post
GET http://localhost:3000/api/posts/62eb671220ca55a00be94152 HTTP/1.1
x-auth-token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZWI2NjQzMjBjYTU1YTAwYmU5NDEzNyIsInVzZXJuYW1lIjoiTGF1cmVuY2UzMyIsImlhdCI6MTY1OTU5NzM1MSwiZXhwIjoxNjU5NTk4MjUxfQ.FtQQSzMg_Kl5r1c5bJgLGynOec9PQ1D_S5eoX9HAbVR1JtpzwoO2Ni3FoRPwRKvMEyxN19rxeTV078jY8LC4t2z0v-h8riLYiiq2x9AweDdGfM0lOpaX2EBb5uXvfyf3HGI_jYmhl77cP_iIu3P3JTL3sWoJ2_z5wjQF8VqHMLWkg_mW6nyrwXj3oHe2VXg1JAeIo1jy2pOPWaEFoEUnkx_FwUGw0kw_b8I9mdALpvTJ91Y6C05LpgkqGmYKPS7pKIH4yn17_Zo0kaNSn_mkubkNdQPTnRAF3fNY2pWNiZCSoHsQB855PwSBN39wHpAQef0su5pBVL0yczA_SzOZ39-2pJ_VhMc2IFnYlxwX2lWmhpru6Lts47OLXUpSc1Cpjt1i2UYaYehqmXTnw7MBcFmwUbXnVvsszY80mtftqC56IhR_JOJ6XIdk_R3Nw96Ibj4RkSfHlOfb5aU9i55wMss5fCDV5siM_pgxun-g3_d9pYhhE8E_-6XoyJoat0Um_Cdn91OCOhj5GCKPGNr7gXJufK8U9c_KLLmj6fGIxdtXx_u3u1IdMbl5VBGlEUT8CH58qf0WVWjYjNsKrWHf1cocOpJDd3fGtlu0VVROFZCgyjpjuzLtNkjoHd1wsTsjP3yZ0eUMM5sJaHc51Q34lbLxDIB5BSwgaIctHQIccWw
Cookie: refresh-token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZWE4Nzg1ZjgyODE0MTQ4NDk5MWQzZiIsInVzZXJuYW1lIjoiTGF1cmVuY2UzMyIsImlhdCI6MTY1OTU4ODM5OCwiZXhwIjoxNjYyMTgwMzk4fQ.euoHep0V7JvBVNx1gmrTi2Tsgc1CqQAIIZR1m_43i_8bSkOYUkhho2ULIEtjn7P9SdxOkU2FITzdD3ODnHlFUaveLyJh_qjt2ZQkXc1AMVf8H6SndsXVb2OIAMI-sjhQLIDqOYHqEmoEeKiOFziBZJZe6PYQOMLiA4cUbTttqqukUj4EtMtlmx0pZWdEeE48hfkjwenJ7BnvqoqchoFrf3ZvIJV9VM9nfzvgunceiGZcs-sCRJWFPwQD7mByosC3B68GR4hSdT91exQ02Nccizj-lM2oJz8J20orYvmOCFOL7UmRKJSY3R2FPctp1xy-t9mfnS0_qpZ2mQEqjkYwoN9f8P6DaBQ6CRs-WYShe8pPBKaeKXExfgmLwo0uuE7zsBUQ3oRLq8b75Z-XiPGvMHo-i0EocN2X8bxdCwNml_FPWCxmSatno1t4BI24AU2jFbXd-7W6fABLW6RE67s_xcbiMGRHgI87TRnE_adiXu8VcKhehv9gecIdbdMCgEOE527zfaZhwxI4ZR_jyL_igb_S3oECZrX6p7w2BgtIzsNj3F9DjolRdY8nnt5WD3GsVdk_QBYAYwuHi-xRGyPT6LW80o7K13GcNseamv8Cbf39wbShD-8RpJY-4F6TT8JxSVy6B8CZzw1UFfrJOu6iMrp_RXG3SsJi2rdRxf2THK8


### Get download links for images of the post
GET http://localhost:3000/api/posts/62eb671220ca55a00be94152/images HTTP/1.1
x-auth-token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZWI2NjQzMjBjYTU1YTAwYmU5NDEzNyIsInVzZXJuYW1lIjoiTGF1cmVuY2UzMyIsImlhdCI6MTY1OTU5NzM1MSwiZXhwIjoxNjU5NTk4MjUxfQ.FtQQSzMg_Kl5r1c5bJgLGynOec9PQ1D_S5eoX9HAbVR1JtpzwoO2Ni3FoRPwRKvMEyxN19rxeTV078jY8LC4t2z0v-h8riLYiiq2x9AweDdGfM0lOpaX2EBb5uXvfyf3HGI_jYmhl77cP_iIu3P3JTL3sWoJ2_z5wjQF8VqHMLWkg_mW6nyrwXj3oHe2VXg1JAeIo1jy2pOPWaEFoEUnkx_FwUGw0kw_b8I9mdALpvTJ91Y6C05LpgkqGmYKPS7pKIH4yn17_Zo0kaNSn_mkubkNdQPTnRAF3fNY2pWNiZCSoHsQB855PwSBN39wHpAQef0su5pBVL0yczA_SzOZ39-2pJ_VhMc2IFnYlxwX2lWmhpru6Lts47OLXUpSc1Cpjt1i2UYaYehqmXTnw7MBcFmwUbXnVvsszY80mtftqC56IhR_JOJ6XIdk_R3Nw96Ibj4RkSfHlOfb5aU9i55wMss5fCDV5siM_pgxun-g3_d9pYhhE8E_-6XoyJoat0Um_Cdn91OCOhj5GCKPGNr7gXJufK8U9c_KLLmj6fGIxdtXx_u3u1IdMbl5VBGlEUT8CH58qf0WVWjYjNsKrWHf1cocOpJDd3fGtlu0VVROFZCgyjpjuzLtNkjoHd1wsTsjP3yZ0eUMM5sJaHc51Q34lbLxDIB5BSwgaIctHQIccWw
Cookie: refresh-token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZWE4Nzg1ZjgyODE0MTQ4NDk5MWQzZiIsInVzZXJuYW1lIjoiTGF1cmVuY2UzMyIsImlhdCI6MTY1OTU4ODM5OCwiZXhwIjoxNjYyMTgwMzk4fQ.euoHep0V7JvBVNx1gmrTi2Tsgc1CqQAIIZR1m_43i_8bSkOYUkhho2ULIEtjn7P9SdxOkU2FITzdD3ODnHlFUaveLyJh_qjt2ZQkXc1AMVf8H6SndsXVb2OIAMI-sjhQLIDqOYHqEmoEeKiOFziBZJZe6PYQOMLiA4cUbTttqqukUj4EtMtlmx0pZWdEeE48hfkjwenJ7BnvqoqchoFrf3ZvIJV9VM9nfzvgunceiGZcs-sCRJWFPwQD7mByosC3B68GR4hSdT91exQ02Nccizj-lM2oJz8J20orYvmOCFOL7UmRKJSY3R2FPctp1xy-t9mfnS0_qpZ2mQEqjkYwoN9f8P6DaBQ6CRs-WYShe8pPBKaeKXExfgmLwo0uuE7zsBUQ3oRLq8b75Z-XiPGvMHo-i0EocN2X8bxdCwNml_FPWCxmSatno1t4BI24AU2jFbXd-7W6fABLW6RE67s_xcbiMGRHgI87TRnE_adiXu8VcKhehv9gecIdbdMCgEOE527zfaZhwxI4ZR_jyL_igb_S3oECZrX6p7w2BgtIzsNj3F9DjolRdY8nnt5WD3GsVdk_QBYAYwuHi-xRGyPT6LW80o7K13GcNseamv8Cbf39wbShD-8RpJY-4F6TT8JxSVy6B8CZzw1UFfrJOu6iMrp_RXG3SsJi2rdRxf2THK8


### Delete a post owned by the logged in user
DELETE http://localhost:3000/api/posts/62eb66e820ca55a00be94145 HTTP/1.1
x-auth-token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZWE4Nzg1ZjgyODE0MTQ4NDk5MWQzZiIsInVzZXJuYW1lIjoiTGF1cmVuY2UzMyIsImlhdCI6MTY1OTU4ODM5OCwiZXhwIjoxNjU5NTg5Mjk4fQ.mx77KQM3FBCniFm9L_Iruw5izDISIw-iAva70vTA_E-DsgOInfgGXAAxscMHEoZxNW41nqKUvFBJvlQG3UnheuUsFMELaS_x6x1j_0zf7ZlITaDWwH_hHCquHNFs1uzAXQJow2H85eyIZAZEdj5RTn7Jod95PAT3pAL4EkoBmZoSfkLkqGG54UI7sGdkOv7DaZ9RPHKt1WdPQSQ0Ck3kGTsf_i50UX0n4sfx_AfTfAUveXNWTssO3AOmTOGdD5kse1u_l_UIsHfxgKFNMZl8yi8nDGUT_lmMGazMeOEdMzxenVpfXIAgWkxDUhdfWAbA5CHAIzIk6-FoHEKPj6faKD4VoENwtGUSy1QS8VX-od8IEzmF8g0FPvLcF2hfhGzgTummzzx6yf9YLEJjeMTjWlmkU48oW4dksazH2GdkXoWlUeUFGc_vQktFdAP5vO7eVWEOMF7Vlu6N0oOBSADWn7opVRKpkjpFqg8cu1GazSN8bTUVi-sWN-DdzaekSuGe6kD_rWxgqIAZvr19kgr-sDDc8bSSdHiEWVjIQq121FdONSBIv063hJ96B1YI_xSWgmcciGcnN-xwxDnxAobr9JGhGDHOiS1ZMAmWoUBGGf1prJEGP3ORaKaLySLyKW5hfoJlywES0NF595LY_-u6dt-WCapi-ldJTLFdp87m3Rk
Cookie: refresh-token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZWE4Nzg1ZjgyODE0MTQ4NDk5MWQzZiIsInVzZXJuYW1lIjoiTGF1cmVuY2UzMyIsImlhdCI6MTY1OTU4ODM5OCwiZXhwIjoxNjYyMTgwMzk4fQ.euoHep0V7JvBVNx1gmrTi2Tsgc1CqQAIIZR1m_43i_8bSkOYUkhho2ULIEtjn7P9SdxOkU2FITzdD3ODnHlFUaveLyJh_qjt2ZQkXc1AMVf8H6SndsXVb2OIAMI-sjhQLIDqOYHqEmoEeKiOFziBZJZe6PYQOMLiA4cUbTttqqukUj4EtMtlmx0pZWdEeE48hfkjwenJ7BnvqoqchoFrf3ZvIJV9VM9nfzvgunceiGZcs-sCRJWFPwQD7mByosC3B68GR4hSdT91exQ02Nccizj-lM2oJz8J20orYvmOCFOL7UmRKJSY3R2FPctp1xy-t9mfnS0_qpZ2mQEqjkYwoN9f8P6DaBQ6CRs-WYShe8pPBKaeKXExfgmLwo0uuE7zsBUQ3oRLq8b75Z-XiPGvMHo-i0EocN2X8bxdCwNml_FPWCxmSatno1t4BI24AU2jFbXd-7W6fABLW6RE67s_xcbiMGRHgI87TRnE_adiXu8VcKhehv9gecIdbdMCgEOE527zfaZhwxI4ZR_jyL_igb_S3oECZrX6p7w2BgtIzsNj3F9DjolRdY8nnt5WD3GsVdk_QBYAYwuHi-xRGyPT6LW80o7K13GcNseamv8Cbf39wbShD-8RpJY-4F6TT8JxSVy6B8CZzw1UFfrJOu6iMrp_RXG3SsJi2rdRxf2THK8


### Search for posts by keywords, date created range, and limit the result. Default limit is 10.
GET http://localhost:3000/api/search?keyword=second HTTP/1.1


### Create post under the logged in user
POST http://localhost:3000/api/posts HTTP/1.1
Content-Type: application/json
x-auth-token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZWE4Nzg1ZjgyODE0MTQ4NDk5MWQzZiIsInVzZXJuYW1lIjoiTGF1cmVuY2UzMyIsImlhdCI6MTY1OTU4ODM5OCwiZXhwIjoxNjU5NTg5Mjk4fQ.mx77KQM3FBCniFm9L_Iruw5izDISIw-iAva70vTA_E-DsgOInfgGXAAxscMHEoZxNW41nqKUvFBJvlQG3UnheuUsFMELaS_x6x1j_0zf7ZlITaDWwH_hHCquHNFs1uzAXQJow2H85eyIZAZEdj5RTn7Jod95PAT3pAL4EkoBmZoSfkLkqGG54UI7sGdkOv7DaZ9RPHKt1WdPQSQ0Ck3kGTsf_i50UX0n4sfx_AfTfAUveXNWTssO3AOmTOGdD5kse1u_l_UIsHfxgKFNMZl8yi8nDGUT_lmMGazMeOEdMzxenVpfXIAgWkxDUhdfWAbA5CHAIzIk6-FoHEKPj6faKD4VoENwtGUSy1QS8VX-od8IEzmF8g0FPvLcF2hfhGzgTummzzx6yf9YLEJjeMTjWlmkU48oW4dksazH2GdkXoWlUeUFGc_vQktFdAP5vO7eVWEOMF7Vlu6N0oOBSADWn7opVRKpkjpFqg8cu1GazSN8bTUVi-sWN-DdzaekSuGe6kD_rWxgqIAZvr19kgr-sDDc8bSSdHiEWVjIQq121FdONSBIv063hJ96B1YI_xSWgmcciGcnN-xwxDnxAobr9JGhGDHOiS1ZMAmWoUBGGf1prJEGP3ORaKaLySLyKW5hfoJlywES0NF595LY_-u6dt-WCapi-ldJTLFdp87m3Rk
Cookie: refresh-token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZWE4Nzg1ZjgyODE0MTQ4NDk5MWQzZiIsInVzZXJuYW1lIjoiTGF1cmVuY2UzMyIsImlhdCI6MTY1OTU4ODM5OCwiZXhwIjoxNjYyMTgwMzk4fQ.euoHep0V7JvBVNx1gmrTi2Tsgc1CqQAIIZR1m_43i_8bSkOYUkhho2ULIEtjn7P9SdxOkU2FITzdD3ODnHlFUaveLyJh_qjt2ZQkXc1AMVf8H6SndsXVb2OIAMI-sjhQLIDqOYHqEmoEeKiOFziBZJZe6PYQOMLiA4cUbTttqqukUj4EtMtlmx0pZWdEeE48hfkjwenJ7BnvqoqchoFrf3ZvIJV9VM9nfzvgunceiGZcs-sCRJWFPwQD7mByosC3B68GR4hSdT91exQ02Nccizj-lM2oJz8J20orYvmOCFOL7UmRKJSY3R2FPctp1xy-t9mfnS0_qpZ2mQEqjkYwoN9f8P6DaBQ6CRs-WYShe8pPBKaeKXExfgmLwo0uuE7zsBUQ3oRLq8b75Z-XiPGvMHo-i0EocN2X8bxdCwNml_FPWCxmSatno1t4BI24AU2jFbXd-7W6fABLW6RE67s_xcbiMGRHgI87TRnE_adiXu8VcKhehv9gecIdbdMCgEOE527zfaZhwxI4ZR_jyL_igb_S3oECZrX6p7w2BgtIzsNj3F9DjolRdY8nnt5WD3GsVdk_QBYAYwuHi-xRGyPT6LW80o7K13GcNseamv8Cbf39wbShD-8RpJY-4F6TT8JxSVy6B8CZzw1UFfrJOu6iMrp_RXG3SsJi2rdRxf2THK8

{
    "title": "My first post",
    "body": "This is my third post."
}


### Register a new user
POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "username": "Laurence33",
    "password": "Pass123@"
}


### Login using username and password
POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "username": "Laurence33",
    "password": "Pass123@"
}

### Try to get all post without logging in, should return 403
POST http://localhost:3000/api/posts HTTP/1.1



### Logout the user
DELETE http://localhost:3000/api/auth/logout HTTP/1.1



